<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { db, id } from '../services/db'
import { useAppStore } from '../stores/app'
import { getOrCreateState, utf8Bytes } from '../services/engine'
import type { Bank, Sentence } from '../types'
const store=useAppStore(),router=useRouter(),banks=ref<Bank[]>([]),counts=ref<Record<string,number>>({}),librarySentences=ref<Sentence[]>([]), selected=ref(''), text=ref(''), meaning=ref(''), source=ref(''), importText=ref(''),message=ref(''),error=ref(''), importFile=ref<HTMLInputElement>(), byteCount=computed(()=>utf8Bytes(text.value))
async function loadSentences(){if(selected.value)librarySentences.value=await db.sentences.where('bankId').equals(selected.value).sortBy('order');else librarySentences.value=[]}
async function load(){await store.refreshBanks();banks.value=store.banks;const c:Record<string,number>={};for(const b of banks.value)c[b.id]=await db.sentences.where('bankId').equals(b.id).count();counts.value=c;await loadSentences()}
async function addBank(){const name=prompt('给新句库起个名字');if(!name?.trim())return;const now=new Date().toISOString(),bank={id:id(),name:name.trim(),description:'自定义句库',kind:'custom' as const,createdAt:now,updatedAt:now};await db.banks.add(bank);selected.value=bank.id;store.setBank(bank.id);await load();message.value='句库已创建'}
async function addSentence(){error.value='';if(!selected.value)return error.value='请先选择一个句库';if(!text.value.trim())return error.value='句子正文不能为空';if(byteCount.value>300)return error.value='句子超过 300 UTF-8 字节';const bankSentences=await db.sentences.where('bankId').equals(selected.value).toArray();const s:Sentence={id:id(),bankId:selected.value,text:text.value.trim(),meaning:meaning.value.trim(),source:source.value.trim(),order:bankSentences.length,createdAt:new Date().toISOString()};await db.transaction('rw',db.sentences,db.cardStates,async()=>{await db.sentences.add(s);await getOrCreateState(s.bankId,s.id)});text.value='';meaning.value='';source.value='';message.value='句子已添加';await load()}
function loadTextFile(event:Event){error.value='';const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;if(!/\.txt$/i.test(file.name)&&file.type!=='text/plain'){error.value='请选择 .txt 文本文件';input.value='';return}const reader=new FileReader();reader.onload=()=>{importText.value=String(reader.result??'').replace(/^\uFEFF/,'');message.value=`已读取 ${file.name}，请确认句子内容和目标句库后导入`};reader.onerror=()=>{error.value='无法读取这个文本文件'};reader.readAsText(file,'UTF-8');input.value=''}
async function batchImport(){error.value='';message.value='';const target=selected.value||store.bankId;const lines=importText.value.replace(/^\uFEFF/,'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return error.value='请粘贴内容或先读取一个 TXT 文件';let parsed:Array<{body:string;translation:string;origin:string}>;if(lines.some(line=>line.includes('||'))){parsed=lines.map(line=>{const [body,translation='',origin='批量导入']=line.split('||').map(x=>x.trim());return {body,translation,origin}})}else{if(lines.length%2!==0)return error.value=`检测到 ${lines.length} 行非空内容；请按“英文一行、中文一行”配对，或补齐第 ${lines.length+1} 行翻译`;parsed=[];for(let i=0;i<lines.length;i+=2)parsed.push({body:lines[i]!,translation:lines[i+1]!,origin:'文本导入'})}const invalid=parsed.findIndex(row=>!row.body||utf8Bytes(row.body)>300);if(invalid>=0)return error.value=`第 ${invalid+1} 句英文正文为空或超过 300 UTF-8 字节`;if(!target)return error.value='请先创建或选择一个句库';const existing=await db.sentences.where('bankId').equals(target).count();await db.transaction('rw',db.sentences,db.cardStates,async()=>{for(const [i,row] of parsed.entries()){const s:Sentence={id:id(),bankId:target,text:row.body,meaning:row.translation,source:row.origin,order:existing+i,createdAt:new Date().toISOString()};await db.sentences.add(s);await getOrCreateState(target,s.id)}});importText.value='';message.value=`已按“英文 + 中文”成对导入 ${parsed.length} 句`;await load()}
async function choose(bankId:string){store.setBank(bankId);await router.push(`/banks/${bankId}/browse`)}
async function editSentence(sentence:Sentence){const next=prompt('编辑句子正文（最多 300 UTF-8 字节）',sentence.text);if(next===null)return;if(!next.trim()||utf8Bytes(next)>300){error.value='句子不能为空，且不能超过 300 UTF-8 字节';return}const translation=prompt('编辑释义',sentence.meaning);if(translation===null)return;const origin=prompt('编辑出处',sentence.source);if(origin===null)return;await db.sentences.update(sentence.id,{text:next.trim(),meaning:translation.trim(),source:origin.trim()});message.value='句子已更新';await loadSentences()}
async function removeSentence(sentence:Sentence){if(!confirm(`从当前句库删除这句话和对应复习进度？\n${sentence.text}`))return;await db.transaction('rw',db.sentences,db.cardStates,db.wrongEntries,async()=>{await db.sentences.delete(sentence.id);await db.cardStates.delete(`${sentence.bankId}:${sentence.id}`);await db.wrongEntries.where('[bankId+sentenceId]').equals([sentence.bankId,sentence.id]).delete();const remaining=await db.sentences.where('bankId').equals(sentence.bankId).sortBy('order');await db.sentences.bulkPut(remaining.map((row,index)=>({...row,order:index}))) });message.value='句子已删除';await load()}
async function deleteBank(bank:Bank){if(bank.kind==='builtin')return;if(!confirm(`删除“${bank.name}”及其本地练习进度？`))return;await db.transaction('rw',[db.banks,db.sentences,db.cardStates,db.wrongEntries,db.testRecords,db.statsDaily],async()=>{await db.banks.delete(bank.id);await db.sentences.where('bankId').equals(bank.id).delete();await db.cardStates.where('bankId').equals(bank.id).delete();await db.wrongEntries.where('bankId').equals(bank.id).delete();await db.testRecords.where('bankId').equals(bank.id).delete();await db.statsDaily.where('bankId').equals(bank.id).delete()});await load();selected.value=store.bankId;await loadSentences()}
onMounted(()=>{selected.value=store.bankId;void load()});watch(selected,()=>{void loadSentences()})
</script>
<template><section class="section-heading"><div><span class="eyebrow">YOUR COLLECTION</span><h2>句库中心</h2><p>不同句库的背诵进度彼此独立。</p></div><button class="button button-dark" @click="addBank">＋ 新建句库</button></section><div class="bank-grid"><article v-for="(bank,i) in banks" :key="bank.id" class="bank-card" :class="'bank-tone-'+(i%4)"><div class="bank-card-top"><span class="bank-icon">{{bank.kind==='builtin'?'✳':'▤'}}</span><button v-if="bank.kind==='custom'" class="icon-button" title="删除句库" @click="deleteBank(bank)">⋯</button></div><div class="bank-kind">{{bank.kind==='builtin'?'出厂内置':'我的句库'}}</div><h3>{{bank.name}}</h3><p>{{bank.description}}</p><div class="bank-card-foot"><span>{{counts[bank.id]||0}} 句</span><button class="text-link" @click="choose(bank.id)">打开句库 →</button></div></article></div>
<div class="split-forms"><section class="panel"><div class="panel-heading"><div><span class="eyebrow">ADD ONE</span><h3>添加一句</h3></div></div><label class="field-label">放入句库<select v-model="selected"><option v-for="b in banks" :key="b.id" :value="b.id">{{b.name}}</option></select></label><label class="field-label">句子正文 <span class="field-meta" :class="{'over-limit':byteCount>300}">{{byteCount}} / 300 字节</span><textarea v-model="text" rows="3" placeholder="输入要背诵的句子"></textarea></label><label class="field-label">释义<input v-model="meaning" placeholder="可选"></label><label class="field-label">出处<input v-model="source" placeholder="书名、章节或自定义标签"></label><button class="button button-dark" @click="addSentence">保存句子</button></section><section class="panel"><div class="panel-heading"><div><span class="eyebrow">BATCH IMPORT</span><h3>批量导入</h3></div><span class="format-badge">英文行 + 中文行</span></div><label class="field-label">导入到<select v-model="selected"><option v-for="b in banks" :key="b.id" :value="b.id">{{b.name}}</option></select></label><textarea v-model="importText" rows="10" class="import-area" placeholder="The more we learn, the more we realise how much we do not know.&#10;我们学得越多，就越意识到自己有很多不知道的东西。&#10;&#10;Although technology has transformed communication.&#10;尽管科技改变了沟通方式。"></textarea><p class="field-help">每两行组成一句：英文原文在上，中文翻译在下。空行会忽略。也兼容旧格式：英文 || 中文 || 出处。</p><div class="import-actions"><label class="button button-outline">选择 TXT 文件<input ref="importFile" type="file" accept=".txt,text/plain" hidden @change="loadTextFile"></label><button class="button button-dark" @click="batchImport">导入句子</button></div></section></div><section v-if="librarySentences.length" class="panel library-panel"><div class="panel-heading"><div><span class="eyebrow">SENTENCE LIST</span><h3>当前句库 · {{librarySentences.length}} 句</h3></div><select v-model="selected"><option v-for="b in banks" :key="b.id" :value="b.id">{{b.name}}</option></select></div><div class="sentence-library"><article v-for="sentence in librarySentences" :key="sentence.id" class="library-row"><span class="library-order">{{String(sentence.order+1).padStart(2,'0')}}</span><div class="library-copy"><b>{{sentence.text}}</b><small>{{sentence.meaning||sentence.source||'暂无释义和出处'}}</small></div><button class="soft-button" @click="editSentence(sentence)">编辑</button><button class="soft-button" @click="removeSentence(sentence)">删除</button></article></div></section><p v-if="message" class="toast-inline">{{message}}</p><p v-if="error" class="error-inline">{{error}}</p></template>
