<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { init, use, type ECharts } from 'echarts/core'
import { CalendarComponent, GridComponent, TooltipComponent, VisualMapComponent } from 'echarts/components'
import { HeatmapChart, LineChart } from 'echarts/charts'
import { CanvasRenderer } from 'echarts/renderers'
import { useAppStore } from '../stores/app'
import { db, today } from '../services/db'
import type { StatsDaily } from '../types'
const store=useAppStore(),chartEl=ref<HTMLElement>(),trendEl=ref<HTMLElement>(),days=ref<StatsDaily[]>([]),allTime=ref({reviews:0,correct:0,mastered:0}),heat=ref<Array<{date:string;value:number}>>([])
const accuracy=computed(()=>allTime.value.reviews?Math.round(allTime.value.correct/allTime.value.reviews*100):0),streak=computed(()=>{let n=0;const active=new Set(days.value.filter(d=>d.reviewed>0).map(d=>d.date));const d=new Date();while(active.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n})
use([CalendarComponent,GridComponent,TooltipComponent,VisualMapComponent,HeatmapChart,LineChart,CanvasRenderer])
let chart:ECharts|undefined,trend:ECharts|undefined
async function load(){days.value=await db.statsDaily.where('[bankId+date]').between([store.bankId,''],[store.bankId,'9999']).toArray();allTime.value={reviews:days.value.reduce((a,d)=>a+d.reviewed,0),correct:days.value.reduce((a,d)=>a+d.correct,0),mastered:await db.cardStates.where('[bankId+mastery]').equals([store.bankId,'mastered']).count()};const values=[];for(let i=89;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const date=d.toISOString().slice(0,10);values.push({date,value:days.value.find(x=>x.date===date)?.reviewed||0})}heat.value=values;await nextTick();draw()}
function draw(){if(chartEl.value){chart?.dispose();chart=init(chartEl.value);chart.setOption({tooltip:{formatter:(p:any)=>`${p.data[0]}<br/>复习 ${p.data[1]} 句`},visualMap:{show:false,min:0,max:10,inRange:{color:['#eeede7','#cedbcf','#8caf91','#52775c']}},calendar:{top:20,left:42,right:20,cellSize:['auto',17],range:[heat.value[0]?.date||today(),heat.value.at(-1)?.date||today()],itemStyle:{borderWidth:3,borderColor:'#fffdfa'},yearLabel:{show:false},monthLabel:{color:'#889088',fontSize:11},dayLabel:{color:'#889088',fontSize:10},splitLine:{show:false}},series:[{type:'heatmap',coordinateSystem:'calendar',data:heat.value.map(d=>[d.date,d.value])}]})}if(trendEl.value){trend?.dispose();trend=init(trendEl.value);const ds=days.value.slice(-14);trend.setOption({grid:{top:22,left:34,right:18,bottom:28},tooltip:{trigger:'axis'},xAxis:{type:'category',data:ds.map(d=>d.date.slice(5)),axisLine:{lineStyle:{color:'#deddd5'}},axisLabel:{color:'#8b8e87'}},yAxis:{type:'value',minInterval:1,splitLine:{lineStyle:{color:'#efeee9'}},axisLabel:{color:'#8b8e87'}},series:[{data:ds.map(d=>d.reviewed),type:'line',smooth:true,symbolSize:7,lineStyle:{color:'#547c5d',width:3},itemStyle:{color:'#547c5d'},areaStyle:{color:'rgba(84,124,93,.12)'}}]})}}
function resize(){chart?.resize();trend?.resize()}
onMounted(()=>{void load();window.addEventListener('resize',resize)});onUnmounted(()=>{chart?.dispose();trend?.dispose();window.removeEventListener('resize',resize)});watch(()=>store.bankId,load)
</script>
<template><section class="section-heading"><div><span class="eyebrow">A RECORD OF YOUR EFFORT</span><h2>学习统计</h2><p>稳稳积累，每一次回忆都有价值。</p></div><span class="streak-badge">✦ {{streak}} 天连续练习</span></section><section class="stat-row stats-totals"><div class="stat-card"><span class="stat-icon lilac">◷</span><div><small>累计复习</small><b>{{allTime.reviews}}</b></div><span class="stat-note">次</span></div><div class="stat-card"><span class="stat-icon sage">✓</span><div><small>回忆正确率</small><b>{{accuracy}}%</b></div><span class="stat-note">累计</span></div><div class="stat-card"><span class="stat-icon peach">✳</span><div><small>熟练句子</small><b>{{allTime.mastered}}</b></div><span class="stat-note">条</span></div></section><div class="chart-grid"><section class="panel chart-panel"><div class="panel-heading"><div><span class="eyebrow">LAST 90 DAYS</span><h3>学习热力图</h3></div><span class="chart-legend">少 <i></i><i></i><i></i> 多</span></div><div ref="chartEl" class="heat-chart"></div></section><section class="panel chart-panel"><div class="panel-heading"><div><span class="eyebrow">RECENT PRACTICE</span><h3>近 14 天复习趋势</h3></div></div><div ref="trendEl" class="trend-chart"></div></section></div><section class="panel badges-panel"><div class="panel-heading"><div><span class="eyebrow">SMALL MILESTONES</span><h3>练习徽章</h3></div></div><div class="badge-row"><div class="badge-item" :class="{'badge-earned':allTime.reviews>=1}"><span>✦</span><b>第一步</b><small>完成第一次复习</small></div><div class="badge-item" :class="{'badge-earned':streak>=7}"><span>☼</span><b>七日相伴</b><small>连续练习 7 天</small></div><div class="badge-item" :class="{'badge-earned':allTime.mastered>=20}"><span>❋</span><b>句子收藏家</b><small>熟练掌握 20 句</small></div></div></section></template>
